// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleAngular.Infrastructure.Database;

namespace SampleAngular.Infrastructure.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190114124459_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("SampleAngular.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SampleAngular.Core.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Desc");

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.Property<decimal>("Rating");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("SampleAngular.Core.Entities.StockCategory", b =>
                {
                    b.Property<int>("StockId");

                    b.Property<int>("CategoryId");

                    b.Property<int>("Id");

                    b.HasKey("StockId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("StockCategories");
                });

            modelBuilder.Entity("SampleAngular.Core.Entities.StockCategory", b =>
                {
                    b.HasOne("SampleAngular.Core.Entities.Category", "Category")
                        .WithMany("StockCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SampleAngular.Core.Entities.Stock", "Stock")
                        .WithMany("StockCategories")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
